// Train the Attention Loom's tiny transformers and export their weights.
//
//   node tools/train.mjs reverse      # JS trainer, ~10 s
//   node tools/train.mjs sort         # JS trainer, ~2 min
//   node tools/train.mjs tinyworld    # writes the corpus, runs tools/train_tinyworld.py (numpy, ~25 min),
//                                     # then tools/analyze-tinyworld.mjs --write-meta
//   node tools/train.mjs all
//
// reverse/sort use EXACTLY the code and default hyper-parameters the in-page Lab
// uses (AM.model.lib.AMTaskLib + transformer.js createTrainer, seed 1), so the
// timing printed here is what the Lab will see (modulo machine speed).
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { spawnSync } from 'node:child_process';
import { loadModelScripts, ROOT } from './vm-load.mjs';

function trainAlgo(taskName, { seed = 1, quiet = false } = {}) {
  const ctx = loadModelScripts({ weights: [] });
  const { AMTensorLib, AMTransformerLib, AMTaskLib } = ctx.AM.model.lib;
  const T = AMTensorLib(), TL = AMTransformerLib(T), tasks = AMTaskLib();
  const t = tasks.task(taskName);
  const model = TL.init(t.model, seed);
  const trainer = TL.createTrainer(model, t.train);
  const rng = T.rng(seed);
  // held-out probe set for the time-to-accuracy curve (same seed offset as the Lab's eval batch)
  const evRng = T.rng(seed + 999);
  const evalBatch = tasks.batchFrom(taskName, Array.from({ length: 512 }, () => tasks.example(taskName, evRng).seq));
  const evalAcc = (bt) => tasks.score(taskName, T.noGrad(() => TL.forward(model, bt.ids, bt.B, bt.T)).logits.data, bt);
  const log = [], milestones = {};
  let trainMs = 0, ema = null;
  for (let step = 1; step <= t.train.total; step++) {
    const bt = tasks.batch(taskName, rng, t.train.batch);
    const t0 = performance.now();
    const res = trainer.step(bt);
    trainMs += performance.now() - t0;
    ema = ema == null ? res.loss : 0.95 * ema + 0.05 * res.loss;
    if (step % 25 === 0 || step === t.train.total) {
      const sc = evalAcc(evalBatch);
      for (const thr of [0.5, 0.9, 0.95, 0.99]) {
        if (sc.seqAcc >= thr && !milestones[thr]) milestones[thr] = { step, seconds: +(trainMs / 1000).toFixed(2) };
      }
      log.push([step, +ema.toFixed(4), +sc.seqAcc.toFixed(4)]);
      if (!quiet && (step % 250 === 0 || step === t.train.total))
        console.log(`  ${taskName} step ${step}  loss ${ema.toFixed(4)}  seq acc ${sc.seqAcc.toFixed(3)}  digit acc ${sc.tokenAcc.toFixed(3)}  ${(trainMs / 1000).toFixed(1)}s`);
    }
  }
  // Final test: 10 000 fresh random inputs (never the training stream: different seed).
  const teRng = T.rng(seed + 31337);
  let seqOk = 0, tokAcc = 0, chunks = 0;
  for (let c = 0; c < 20; c++) {
    const bt = tasks.batchFrom(taskName, Array.from({ length: 500 }, () => tasks.example(taskName, teRng).seq));
    const sc = evalAcc(bt);
    seqOk += sc.seqAcc * 500; tokAcc += sc.tokenAcc; chunks++;
  }
  const test = { n: 10000, seqAcc: seqOk / 10000, digitAcc: tokAcc / chunks };
  const msPerStep = trainMs / t.train.total;
  console.log(`${taskName}: params ${TL.countParams(model)}, ${t.train.total} steps in ${(trainMs / 1000).toFixed(1)} s (${msPerStep.toFixed(1)} ms/step)`);
  console.log(`  test exact-sequence acc ${(100 * test.seqAcc).toFixed(2)}%  digit acc ${(100 * test.digitAcc).toFixed(2)}%`);
  console.log('  time to accuracy (held-out, seq exact):', JSON.stringify(milestones));

  const meta = {
    name: taskName, kind: 'char',
    description: taskName === 'reverse'
      ? 'Char-level digit reversal. Input: 8 random digits, then ">", then the same digits reversed, e.g. "38152907>70925183". Loss only on the 8 output positions.'
      : 'Char-level digit sorting. Input: 8 random digits (repeats allowed), then ">", then the digits sorted ascending, e.g. "73519273>12335779". Loss only on the 8 output positions.',
    format: { input_len: t.len, separator: '>', model_reads: 2 * t.len, loss_positions: `${t.len}..${2 * t.len - 1}` },
    params: TL.countParams(model),
    train: Object.assign({ steps: t.train.total, seed, trainer: 'JS (js/model/tensor.js), same code path as the Lab' }, t.train),
    final_train_loss: +ema.toFixed(5),
    test_accuracy: { n: test.n, exact_sequence: +test.seqAcc.toFixed(4), digit: +test.digitAcc.toFixed(4) },
    node_timing: { ms_per_step: +msPerStep.toFixed(2), time_to_accuracy: milestones, node: process.version, cpu: os.cpus()[0].model },
    loss_curve: log.filter((_, i) => i % 4 === 3 || i === log.length - 1),
  };
  const obj = { config: model.config, vocab: t.vocab, meta, tensors: TL.exportWeights(model, true) };
  delete obj.config.init_std;
  const file = path.join(ROOT, `js/model/weights-${taskName}.js`);
  fs.writeFileSync(file, `/* The Attention Loom — trained weights for the "${taskName}" model.\n * Generated by tools/train.mjs — do not edit by hand. float32 little-endian, base64. */\n` +
    `(window.AM_WEIGHTS = window.AM_WEIGHTS || {}).${taskName} = ${JSON.stringify(obj)};\n`);
  console.log(`  wrote ${path.relative(ROOT, file)} (${fs.statSync(file).size} bytes)`);
  return meta;
}

function trainTinyworld(extra) {
  const dataDir = path.join(os.tmpdir(), 'attention-loom-data');
  let r = spawnSync(process.execPath, [path.join(ROOT, 'tools/data-tinyworld.mjs'), '--out', dataDir], { stdio: 'inherit' });
  if (r.status) process.exit(r.status);
  r = spawnSync('python3', [path.join(ROOT, 'tools/train_tinyworld.py'), '--data', dataDir, ...extra], { stdio: 'inherit' });
  if (r.status) process.exit(r.status);
  // measure which heads do what and store it in meta.analysis
  r = spawnSync(process.execPath, [path.join(ROOT, 'tools/analyze-tinyworld.mjs'), '--write-meta'], { stdio: 'inherit' });
  if (r.status) process.exit(r.status);
}

const [what = 'all', ...rest] = process.argv.slice(2);
if (what === 'reverse' || what === 'all') trainAlgo('reverse');
if (what === 'sort' || what === 'all') trainAlgo('sort');
if (what === 'tinyworld' || what === 'all') trainTinyworld(rest);
